output_folder: "../logs"
dataset:
  name: "COCO"

  img_folder: "../data/coco/images"
  json_folder: "../data/coco/annotations"
  train: "train"
  test: "val"

# other parameters can be specified in this yaml file
# e.g. the following lines will reset the number of training epochs to 8
#opt:
#  epochs: 8
loader:
  batch_size: 32
model:
  backbone: resnet34
  num_classes: 80

# see config.py for more details
